connect ralu_p01/ralu

Prompt TABLE: ENTIDAD_NACIMIENTO 

CREATE TABLE ENTIDAD_NACIMIENTO(
    ENTIDAD_NACIMIENTO_ID    NUMBER(30, 0)    NOT NULL,
    ENTIDAD                  VARCHAR2(30)     NOT NULL,
    CONSTRAINT ENTIDAD_NACIMIENTO_PK PRIMARY KEY (ENTIDAD_NACIMIENTO_ID)
    USING INDEX(
    CREATE UNIQUE INDEX ENTIDAD_NACIMIENTO_PK ON ENTIDAD_NACIMIENTO(ENTIDAD_NACIMIENTO_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

Prompt TABLE: NIVEL_ESTUDIO 

CREATE TABLE NIVEL_ESTUDIO(
    NIVEL_ESTUDIO_ID    NUMBER(30, 0)    NOT NULL,
    NIVEL_ESTUDIO       VARCHAR2(80)     NOT NULL,
    CONSTRAINT NIVEL_ESTUDIO_PK PRIMARY KEY (NIVEL_ESTUDIO_ID)
    USING INDEX(
    CREATE UNIQUE INDEX NIVEL_ESTUDIO_PK ON NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

Prompt TABLE: ESTATUS_PROVEEDOR 

CREATE TABLE ESTATUS_PROVEEDOR(
    ESTATUS_PROVEEDOR_ID    NUMBER(30, 0)    NOT NULL,
    DESCRIPCION             VARCHAR2(15)     NOT NULL,
    CONSTRAINT ESTATUS_PROVEEDOR_PK PRIMARY KEY (ESTATUS_PROVEEDOR_ID)
    USING INDEX(
    CREATE UNIQUE INDEX ESTATUS_PROVEEDOR_PK ON ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

Prompt TABLE: PROVEEDOR 

CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID             NUMBER(20, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(20)     NOT NULL,
    AP_PATERNO               VARCHAR2(20)     NOT NULL,
    AP_MATERNO               VARCHAR2(20)     NOT NULL,
    FOTO                     BLOB             NOT NULL,
    FECHA_NACIMIENTO         DATE             NOT NULL,
    DIRECCION                VARCHAR2(150)    NOT NULL,
    TELEFONO_CASA            NUMBER(10, 0)    NOT NULL,
    TELEFONO_MOVIL           NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS             DATE             NOT NULL,
    ENTIDAD_NACIMIENTO_ID    NUMBER(30, 0)    NOT NULL,
    NIVEL_ESTUDIO_ID         NUMBER(30, 0)    NOT NULL,
    ESTATUS_PROVEEDOR_ID     NUMBER(30, 0)    NOT NULL,
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (PROVEEDOR_ID)
    USING INDEX(
    CREATE UNIQUE INDEX PROVEEDOR_PK ON PROVEEDOR(PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT PROVEEDOR_ENTIDAD_NACIMIENTO_ID_FK FOREIGN KEY (ENTIDAD_NACIMIENTO_ID)
    REFERENCES ENTIDAD_NACIMIENTO(ENTIDAD_NACIMIENTO_ID),
    CONSTRAINT PROVEEDOR_NIVEL_ESTUDIO_ID_FK FOREIGN KEY (NIVEL_ESTUDIO_ID)
    REFERENCES NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID),
    CONSTRAINT PROVEEDOR_ESTATUS_PROVEEDOR_ID_FK FOREIGN KEY (ESTATUS_PROVEEDOR_ID)
    REFERENCES ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

CREATE INDEX PROVEEDOR_ENTIDAD_NACIMIENTO_ID_FK ON PROVEEDOR(ENTIDAD_NACIMIENTO_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

CREATE INDEX PROVEEDOR_NIVEL_ESTUDIO_ID_FK ON PROVEEDOR(NIVEL_ESTUDIO_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

CREATE INDEX PROVEEDOR_ESTATUS_PROVEEDOR_ID_FK ON PROVEEDOR(ESTATUS_PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

Prompt TABLE: TIPO_SERVICIO 

CREATE TABLE TIPO_SERVICIO(
    TIPO_SERVICIO_ID    NUMBER(30, 0)    NOT NULL,
    NOMBRE              VARCHAR2(30)     NOT NULL,
    DESCRIPCION         VARCHAR2(150)    NOT NULL,
    AÑOS_EXPERIENCIA    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT TIPO_SERVICIO_PK PRIMARY KEY (TIPO_SERVICIO_ID)
    USING INDEX(
    CREATE UNIQUE INDEX TIPO_SERVICIO_PK ON TIPO_SERVICIO(TIPO_SERVICIO_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

Prompt TABLE: PROVEEDOR_TIPO_SERVICIO 

CREATE TABLE PROVEEDOR_TIPO_SERVICIO(
    PROVEEDOR_TIPO_SERVICIO_ID    NUMBER(30, 0)    NOT NULL,
    PROVEEDOR_ID                  NUMBER(20, 0)    NOT NULL,
    TIPO_SERVICIO_ID              NUMBER(30, 0)    NOT NULL,
    CONSTRAINT PROVEEDOR_TIPO_SERVICIO_PK PRIMARY KEY (PROVEEDOR_TIPO_SERVICIO_ID)
    USING INDEX(
    CREATE UNIQUE INDEX PROVEEDOR_TIPO_SERVICIO_PK ON PROVEEDOR_TIPO_SERVICIO(PROVEEDOR_TIPO_SERVICIO_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT PROVEEDOR_TIPO_SERVICIO_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT PROVEEDOR_TIPO_SERVICIO_TIPO_SERVICIO_ID_FK FOREIGN KEY (TIPO_SERVICIO_ID)
    REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

CREATE INDEX PROVEEDOR_TIPO_SERVICIO_PROVEEDOR_ID_FK ON PROVEEDOR_TIPO_SERVICIO(PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

CREATE INDEX PROVEEDOR_TIPO_SERVICIO_TIPO_SERVICIO_ID_FK ON PROVEEDOR_TIPO_SERVICIO(TIPO_SERVICIO_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

Prompt TABLE: COMP_EXP_PROVEEDOR 

CREATE TABLE COMP_EXP_PROVEEDOR(
    COMP_EXP_PROVEEDOR_ID         NUMBER(30, 0)    NOT NULL,
    COMPROBANTE_PDF               BLOB             NOT NULL,
    PROVEEDOR_TIPO_SERVICIO_ID    NUMBER(30, 0)    NOT NULL,
    CONSTRAINT COMP_EXP_PROVEEDOR_PK PRIMARY KEY (COMP_EXP_PROVEEDOR_ID)
    USING INDEX(
    CREATE UNIQUE INDEX COMP_EXP_PROVEEDOR_PK ON COMP_EXP_PROVEEDOR(COMP_EXP_PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT COMP_EXP_PROVEEDOR_PROVEEDOR_TIPO_SERVICIO_ID_FK FOREIGN KEY (PROVEEDOR_TIPO_SERVICIO_ID)
    REFERENCES PROVEEDOR_TIPO_SERVICIO(PROVEEDOR_TIPO_SERVICIO_ID)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

CREATE INDEX COMP_EXP_PROVEEDOR_PROVEEDOR_TIPO_SERVICIO_ID_FK ON COMP_EXP_PROVEEDOR(PROVEEDOR_TIPO_SERVICIO_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

Prompt TABLE: DEPOSITO_PROV 

CREATE TABLE DEPOSITO_PROV(
    DEPOSITO_PROV_ID    NUMBER(30, 0)    NOT NULL,
    IMPORTE             NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO          DATE             NOT NULL,
    COMPROBANTE         RAW(30)          NOT NULL,
    PROVEEDOR_ID        NUMBER(20, 0)    NOT NULL,
    CONSTRAINT DEPOSITO_PROV_PK PRIMARY KEY (DEPOSITO_PROV_ID)
    USING INDEX(
    CREATE UNIQUE INDEX DEPOSITO_PROV_PK ON DEPOSITO_PROV(DEPOSITO_PROV_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT DEPOSITO_PROV_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

CREATE INDEX DEPOSITO_PROV_PROVEEDOR_ID_FK ON DEPOSITO_PROV(PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

grant references on PROVEEDOR to ralu_p02;

connect ralu_p02/ralu
Prompt TABLE: DOC_PROVEEDOR 

CREATE TABLE DOC_PROVEEDOR(
    DOC_PROVEEDOR_ID         NUMBER(30, 0)    NOT NULL,
    IDENTIFICACION           BLOB             NOT NULL,
    COMPROBANTE_DOMICILIO    BLOB             NOT NULL,
    CLABE                    NUMBER(18, 0)    NOT NULL,
    BANCO                    VARCHAR2(30)     NOT NULL,
    PROVEEDOR_ID             NUMBER(20, 0)    NOT NULL,
    CONSTRAINT DOC_PROVEEDOR_PK PRIMARY KEY (DOC_PROVEEDOR_ID)
    USING INDEX(
    CREATE UNIQUE INDEX DOC_PROVEEDOR_PK ON DOC_PROVEEDOR(DOC_PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT DOC_PROVEEDOR_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES RALU_P01.PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT DOC_PROVEEDOR_CLABE_UK UNIQUE(CLABE)
)TABLESPACE PROVEEDOR_BIG_TBS;

CREATE INDEX DOC_PROVEEDOR_PROVEEDOR_ID_FK ON DOC_PROVEEDOR(PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

connect ralu_p01/ralu
Prompt TABLE: EMAIL_PROVEEDOR 

CREATE TABLE EMAIL_PROVEEDOR(
    EMAIL_PROVEEDOR_ID    NUMBER(30, 0)    NOT NULL,
    EMAIL_1               VARCHAR2(40)     NOT NULL,
    EMAIL_2               VARCHAR2(40),
    EMAIL_3               VARCHAR2(40),
    PROVEEDOR_ID          NUMBER(20, 0)    NOT NULL,
    CONSTRAINT EMAIL_PROVEEDOR_PK PRIMARY KEY (EMAIL_PROVEEDOR_ID)
    USING INDEX(
    CREATE UNIQUE INDEX EMAIL_PROVEEDOR_PK ON EMAIL_PROVEEDOR(EMAIL_PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT EMAIL_PROVEEDOR_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

CREATE INDEX EMAIL_PROVEEDOR_PROVEEDOR_ID_FK ON EMAIL_PROVEEDOR(PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

Prompt TABLE: EVIDENCIA_SERV_PROV 

CREATE TABLE EVIDENCIA_SERV_PROV(
    EVIDENCIA_SERV_PROV_ID    NUMBER(30, 0)    NOT NULL,
    DESCRIPCION               VARCHAR2(500)    NOT NULL,
    FECHA_ELABORACION         DATE             NOT NULL,
    PROVEEDOR_ID              NUMBER(20, 0)    NOT NULL,
    CONSTRAINT EVIDENCIA_SERV_PROV_PK PRIMARY KEY (EVIDENCIA_SERV_PROV_ID)
    USING INDEX(
    CREATE UNIQUE INDEX EVIDENCIA_SERV_PROV_PK ON EVIDENCIA_SERV_PROV(EVIDENCIA_SERV_PROV_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT EVIDENCIA_SERV_PROV_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

CREATE INDEX EVIDENCIA_SERV_PROV_PROVEEDOR_ID_FK ON EVIDENCIA_SERV_PROV(PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

Prompt TABLE: HIST_ESTATUS_PROVEEDOR 

CREATE TABLE HIST_ESTATUS_PROVEEDOR(
    HIST_ESTATUS_PROVEEDOR_ID    NUMBER(30, 0)    NOT NULL,
    FECHA_ESTATUS                DATE             NOT NULL,
    ESTATUS_PROVEEDOR_ID         NUMBER(30, 0)    NOT NULL,
    PROVEEDOR_ID                 NUMBER(20, 0)    NOT NULL,
    CONSTRAINT HIST_ESTATUS_PROVEEDOR_PK PRIMARY KEY (HIST_ESTATUS_PROVEEDOR_ID)
    USING INDEX(
    CREATE UNIQUE INDEX HIST_ESTATUS_PROVEEDOR_PK ON HIST_ESTATUS_PROVEEDOR(HIST_ESTATUS_PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT HIST_ESTATUS_PROVEEDOR_ESTATUS_PROVEEDOR_ID_FK FOREIGN KEY (ESTATUS_PROVEEDOR_ID)
    REFERENCES ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID),
    CONSTRAINT HIST_ESTATUS_PROVEEDOR_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;

CREATE INDEX HIST_ESTATUS_PROVEEDOR_ESTATUS_PROVEEDOR_ID_FK ON HIST_ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

CREATE INDEX HIST_ESTATUS_PROVEEDOR_PROVEEDOR_ID_FK ON HIST_ESTATUS_PROVEEDOR(PROVEEDOR_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS;

Prompt TABLE: IMAGEN_EVIDENCIA_SERVICIO 

CREATE TABLE IMAGEN_EVIDENCIA_SERVICIO(
    EVIDENCIA_SERV_PROV_ID    NUMBER(30, 0)    NOT NULL,
    IMAGEN                    BLOB             NOT NULL,
    IMAGEN_ID                 NUMBER(30, 0)    NOT NULL,
    DESCRIPCION               VARCHAR2(150)    NOT NULL,
    CONSTRAINT IMAGEN_EVIDENCIA_SERVICIO_PK PRIMARY KEY (EVIDENCIA_SERV_PROV_ID)
    USING INDEX(
    CREATE UNIQUE INDEX IMAGEN_EVIDENCIA_SERVICIO_PK ON IMAGEN_EVIDENCIA_SERVICIO(EVIDENCIA_SERV_PROV_ID)
    TABLESPACE PROVEEDOR_INDICES_TBS), 
    CONSTRAINT IMAGEN_EVIDENCIA_SERVICIO_EVIDENCIA_SERV_PROV_ID_FK FOREIGN KEY (EVIDENCIA_SERV_PROV_ID)
    REFERENCES EVIDENCIA_SERV_PROV(EVIDENCIA_SERV_PROV_ID)
)TABLESPACE PROVEEDOR_MULTIPLE_TBS;
