-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM-FI
-- Project :      house_services.DM1
-- Author :       abraham
--
-- Date Created : Saturday, January 14, 2023 11:41:04
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CLIENTE 
--
connect ralu_s01/ralu_s01

CREATE TABLE CLIENTE(
    CLIENTE_ID        NUMBER(30, 0)    NOT NULL,
    FECHA_REGISTRO    DATE             NOT NULL,
    NOMBRE_USUARIO    VARCHAR2(30)     NOT NULL,
    CONTRASENA        VARCHAR2(30)     NOT NULL,
    EMAIL             VARCHAR2(30)     NOT NULL,
    TELEFONO          NUMBER(10, 0)    NOT NULL,
    DIRECCION         VARCHAR2(150)    NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
    USING INDEX ( 
        CREATE UNIQUE INDEX CLIENTE_PK ON CLIENTE(CLIENTE_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    )
) TABLESPACE SERVICIO_MULTIPLE_TBS
;




-- 
-- TABLE: COTIZACION_SERVICIO 
--

CREATE TABLE COTIZACION_SERVICIO(
    COTIZACION_SERVICIO_ID    NUMBER(30, 0)    NOT NULL,
    PRECIO                    NUMBER(10, 0)    NOT NULL,
    DESCRIPCION               VARCHAR2(150)    NOT NULL,
    MENSUALIDADES             NUMBER(2, 0),
    SERVICIO_ID               NUMBER(30, 0)    NOT NULL,
    CONSTRAINT COTIZACION_SERVICIO_PK PRIMARY KEY (COTIZACION_SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX COTIZACION_SERVICIO_PK ON COTIZACION_SERVICIO(COTIZACION_SERVICIO_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_MULTIPLE_TBS
)
;




-- 
-- TABLE: EMPRESA 
--

CREATE TABLE EMPRESA(
    CLIENTE_ID          NUMBER(30, 0)    NOT NULL,
    NOMBRE_EMPRESA      VARCHAR2(30)     NOT NULL,
    LOGOTIPO            BLOB             NOT NULL,
    NUMERO_EMPLEADOS    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EMPRESA_PK PRIMARY KEY (CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX EMPRESA_PK ON EMPRESA(EMPRESA_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_MULTIPLE_TBS
)
;


-- 
-- TABLE: ESTATUS_SERVICIO 
--

CREATE TABLE ESTATUS_SERVICIO(
    ESTATUS_SERVICIO_ID    VARCHAR2(30)    NOT NULL,
    DESCRIPCION            VARCHAR2(15)    NOT NULL,
    CONSTRAINT ESTATUS_SERVICIO_PK PRIMARY KEY (ESTATUS_SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ESTATUS_SERVICIO_ESTATUS_SERVICIO_ID ON ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_MULTIPLE_TBS
)
;


-- 
-- TABLE: HIST_ESTATUS_SERVICIO 
--

CREATE TABLE HIST_ESTATUS_SERVICIO(
    HIST_ESTATUS_SERVICIO    NUMBER(30, 0)    NOT NULL,
    FECHA_ESTATUS            DATE             NOT NULL,
    SERVICIO_ID              NUMBER(30, 0)    NOT NULL,
    ESTATUS_SERVICIO_ID      VARCHAR2(30)     NOT NULL,
    CONSTRAINT HIST_ESTATUS_SERVICIO_PK PRIMARY KEY (HIST_ESTATUS_SERVICIO)
    USING INDEX (
        CREATE UNIQUE INDEX  HIST_ESTATUS_SERVICIO_PK  ON HIST_ESTATUS_SERVICIO(HIST_ESTATUS_SERVICIO_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_MULTIPLE_TBS
)
;


-- 
-- TABLE: PAGO 
--

CREATE TABLE PAGO(
    SERVICIO_ID           NUMBER(30, 0)    NOT NULL,
    TARJETA_CLIENTE_ID    NUMBER(30, 0)    NOT NULL,
    NUMERO_PAGO           NUMBER(2, 0)     NOT NULL,
    FECHA_PAGO            DATE             NOT NULL,
    IMPORTE               NUMBER(10, 0)    NOT NULL,
    COMISION              NUMBER(5, 0)     NOT NULL,
    CONSTRAINT PAGO_PK PRIMARY KEY (SERVICIO_ID, TARJETA_CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX PAGO_PK ON PAGO(PAGO_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_MULTIPLE_TBS
)
;



-- 
-- TABLE: PERSONA_FISICA 
--

CREATE TABLE PERSONA_FISICA(
    CLIENTE_ID          NUMBER(30, 0)    NOT NULL,
    NOMBRE              VARCHAR2(30)     NOT NULL,
    FOTO                BLOB             NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT PERSONA_FISICA_PK PRIMARY KEY (CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX PERSONA_FISICA_PK ON PERSONA_FISICA(CLIENTE_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_MULTIPLE_TBS
)
;


-- 
-- TABLE: RESULTADO_SERVICIO 
--

CREATE TABLE RESULTADO_SERVICIO(
    RESULTADO_SERVICIO_ID    NUMBER(30, 0)    NOT NULL,
    COMENTARIO               VARCHAR2(150)    NOT NULL,
    CALIFICACION             NUMBER(1, 0)     NOT NULL,
    SERVICIO_ID              NUMBER(30, 0)    NOT NULL,
    CONSTRAINT RESULTADO_SERVICIO_PK PRIMARY KEY (RESULTADO_SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX RESULTADO_SERVICIO_PK ON RESULTADO_SERVICIO(RESULTADO_SERVICIO_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_MULTIPLE_TBS
)
;



-- 
-- TABLE: SERVICIO 
--

CREATE TABLE SERVICIO(
    SERVICIO_ID              NUMBER(30, 0)     NOT NULL,
    FECHA_SERVICIO           DATE              NOT NULL,
    DESCRIPCION              VARCHAR2(1000)    NOT NULL,
    DESCRIPCION_DETALLADA    RAW(30)           NOT NULL,
    FECHA_STATUS             DATE              NOT NULL,
    ESTATUS_SERVICIO_ID      VARCHAR2(30)      NOT NULL,
    PROVEEDOR_ID             NUMBER(20, 0)     NOT NULL,
    CLIENTE_ID               NUMBER(30, 0)     NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_SERVICIO_PK ON SERVICIO(SERVICIO_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_MULTIPLE_TBS
)
;

-- 
-- TABLE: TARJETA_CLIENTE 
--
connect ralu_s02/ralu_s02
connect ralu_s01/ralu_s01
CREATE TABLE TARJETA_CLIENTE(
    TARJETA_CLIENTE_ID    NUMBER(30, 0)    NOT NULL,
    NUMERO_TARJETA        NUMBER(16, 0)    NOT NULL,
    CLIENTE_ID            NUMBER(30, 0)    NOT NULL,
    CONSTRAINT TARJETA_CLIENTE_PK PRIMARY KEY (TARJETA_CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX TARJETA_CLIENTE_PK ON TARJETA_CLIENTE(TARJETA_CLIENTE_ID)
        TABLESPACE SERVICIO_INDEXES_TBS
    ) TABLESPACE SERVICIO_COMPRESS_TBS
)
;


-- 
-- TABLE: COTIZACION_SERVICIO 
--

ALTER TABLE COTIZACION_SERVICIO ADD CONSTRAINT COTIZACION_SERVICIO_SERVICIO_ID_FK 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
;
 
CREATE INDEX COTIZACION_SERVICIO_SERVICIO_ID_FK ON COTIZACION_SERVICIO(SERVICIO_ID)
TABLESPACE SERVICIO_INDEXES_TBS;



-- 
-- TABLE: EMPRESA 
--

ALTER TABLE EMPRESA ADD CONSTRAINT EMPRESA_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
;




-- 
-- TABLE: HIST_ESTATUS_SERVICIO 
--

ALTER TABLE HIST_ESTATUS_SERVICIO ADD CONSTRAINT HIST_ESTATUS_SERVICIO_SERVICIO_ID_FK 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
;

CREATE INDEX HIST_ESTATUS_SERVICIO_SERVICIO_ID_FK ON HIST_ESTATUS_SERVICIO(SERVICIO_ID)
TABLESPACE SERVICIO_INDEXES_TBS;

ALTER TABLE HIST_ESTATUS_SERVICIO ADD CONSTRAINT HIST_ESTATUS_SERVICIO_ESTATUS_SERVICIO_ID_FK 
    FOREIGN KEY (ESTATUS_SERVICIO_ID)
    REFERENCES ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
;

CREATE INDEX HIST_ESTATUS_SERVICIO_ESTATUS_SERVICIO_ID_FK ON HIST_ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
TABLESPACE SERVICIO_INDEXES_TBS;




-- 
-- TABLE: PAGO 
--

ALTER TABLE PAGO ADD CONSTRAINT PAGO_SERVICIO_ID_FK 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
;

CREATE INDEX PAGO_SERVICIO_ID_FK ON PAGO(SERVICIO_ID)
TABLESPACE SERVICIO_INDEXES_TBS;

ALTER TABLE PAGO ADD CONSTRAINT PAGO_TARJETA_CLIENTE_ID_FK 
    FOREIGN KEY (TARJETA_CLIENTE_ID)
    REFERENCES TARJETA_CLIENTE(TARJETA_CLIENTE_ID)
;

CREATE INDEX PAGO_TARJETA_CLIENTE_ID_FK ON PAGO(TARJETA_CLIENTE_ID)
TABLESPACE SERVICIO_INDEXES_TBS;

-- 
-- TABLE: PERSONA_FISICA 
--

ALTER TABLE PERSONA_FISICA ADD CONSTRAINT PERSONA_FISICA_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
;

-- 
-- TABLE: RESULTADO_SERVICIO 
--

ALTER TABLE RESULTADO_SERVICIO ADD CONSTRAINT RESULTADO_SERVICIO_SERVICIO_ID_FK 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
;
CREATE INDEX RESULTADO_SERVICIO_SERVICIO_ID ON RESULTADO_SERVICIO(SERVICIO_ID)
TABLESPACE SERVICIO_INDEXES_TBS;

-- 
-- TABLE: SERVICIO 
--

ALTER TABLE SERVICIO ADD CONSTRAINT SERVICIO_PROVEEDOR_ID_KF 
    FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
;

CREATE INDEX SERVICIO_CLIENTE_ID_FK ON SERVICIO(PROVEEDOR_ID)
TABLESPACE SERVICIO_INDEXES_TBS;

ALTER TABLE SERVICIO ADD CONSTRAINT SERVICIO_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
;
CREATE INDEX SERVICIO_CLIENTE_ID_FK ON SERVICIO(CLIENTE_ID)
TABLESPACE SERVICIO_INDEXES_TBS;

ALTER TABLE SERVICIO ADD CONSTRAINT SERVICIO_ESTATUS_SERVICIO_ID_FK 
    FOREIGN KEY (ESTATUS_SERVICIO_ID)
    REFERENCES ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
;
CREATE INDEX SERVICIO_ESTATUS_SERVICIO_ID_FK ON SERVICIO(ESTATUS_SERVICIO_ID)
TABLESPACE SERVICIO_INDEXES_TBS;

-- 
-- TABLE: TARJETA_CLIENTE 
--

ALTER TABLE TARJETA_CLIENTE ADD CONSTRAINT TARJETA_CLIENTE_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
;

CREATE INDEX TARJETA_CLIENTE_CLIENTE_ID_FK ON TARJETA_CLIENTE(CLIENTE_ID)
TABLESPACE SERVICIO_INDEXES_TBS;


CREATE UNIQUE INDEX PERSONA_FISICA_CURP_UK ON
PERSONA_FISICA(CURP) TABLESPACE SERVICIO_INDEXES_TBS;

CREATE UNIQUE INDEX TARJETA_CLIENTE_NUMERO_TARJETA_UK ON
TARJETA_CLIENTE(NUMERO_TARJETA) TABLESPACE SERVICIO_INDEXES_TBS;
